# -*- coding: utf-8 -*-
"""octagon-ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MLbw80Fg4f69yUQMLpFZfRLoI7Q8vkVU

1. Setup & Imports
"""

# UFC AI Project - Training & Hypothetical Fight Prediction
# Running in Google Colab

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay
import xgboost as xgb

plt.style.use('seaborn-v0_8-whitegrid')

"""2. Load & Inspect Data"""

from google.colab import files
uploaded = files.upload()
df = pd.read_csv("ufc_stats.csv")

"""3. Data Cleaning"""

# Clean fighter names
df['fighter'] = df['fighter'].str.strip().str.lower().str.replace('"', '', regex=False)
df['winner'] = df['winner'].str.strip().str.lower().str.replace('"', '', regex=False)

# Keep only completed fights
df = df[df['winner'].notnull() & df['winner'].isin(['w', 'l'])]
df.head()

"""4. Feature Engineering"""

numeric_cols = [
    'knockdowns', 'significant_strikes_landed', 'significant_strikes_attempted',
    'significant_strikes_rate', 'total_strikes_landed', 'total_strikes_attempted',
    'takedown_successful', 'takedown_attempted', 'takedown_rate',
    'submission_attempt', 'reversals', 'head_landed', 'body_landed',
    'leg_landed', 'distance_landed', 'clinch_landed', 'ground_landed'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['sig_strike_accuracy'] = df['significant_strikes_landed'] / (df['significant_strikes_attempted'] + 1)
df['takedown_accuracy'] = df['takedown_successful'] / (df['takedown_attempted'] + 1)

"""5. Build Fight-Level Dataset"""

rows = []
for fight_id in df['id'].unique():
    fight_df = df[df['id'] == fight_id]
    if len(fight_df) != 2:
        continue
    f1, f2 = fight_df.iloc[0], fight_df.iloc[1]
    target = 1 if f1['winner'] == 'l' else 0
    row = {f"f1_{c}": f1[c] for c in numeric_cols}
    row.update({f"f2_{c}": f2[c] for c in numeric_cols})
    row['target'] = target
    rows.append(row)

model_df = pd.DataFrame(rows)
model_df['target'].value_counts(normalize=True)

"""Check class balance"""

model_df['target'].value_counts(normalize=True).plot(kind='bar', title='Target Distribution')
plt.show()

"""6. Model Training"""

X = model_df.drop(columns='target')
y = model_df['target']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

model = xgb.XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.1,
    eval_metric='logloss'
)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

ConfusionMatrixDisplay.from_predictions(y_test, y_pred)
plt.show()
xgb.plot_importance(model, max_num_features=15)
plt.show()

"""7. Aggregate Fighter Stats"""

fighter_stats = df.groupby('fighter').agg({col: 'mean' for col in numeric_cols}).reset_index()
fighter_stats.head()

"""8. Hypothetical Fight Predictor"""

def predict_fight(f1_name, f2_name):
    f1, f2 = f1_name.lower(), f2_name.lower()
    if f1 not in fighter_stats['fighter'].values or f2 not in fighter_stats['fighter'].values:
        raise ValueError("Missing fighter stats.")
    f1_row = fighter_stats[fighter_stats['fighter'] == f1].iloc[0]
    f2_row = fighter_stats[fighter_stats['fighter'] == f2].iloc[0]
    f1_feats = {f"f1_{col}": f1_row[col] for col in numeric_cols}
    f2_feats = {f"f2_{col}": f2_row[col] for col in numeric_cols}
    X_new = pd.DataFrame([{**f1_feats, **f2_feats}])
    pred = model.predict(X_new)[0]
    prob = model.predict_proba(X_new)[0]
    return {
      'winner': f1_name if pred == 1 else f2_name,
      'prob_f1': float(prob[1]),
      'prob_f2': float(prob[0])
  }


print(predict_fight("Islam Makhachev", "Jack Della Maddalena"))
print(predict_fight("Jon Jones", "Tai Tuivasa"))
print(predict_fight("Alexander Volkanovski", "Brian Ortega"))
print(predict_fight("Sean Strickland", "Khamzat Chimaev"))
print(predict_fight("Charles Oliveira", "Dustin Poirier"))

"""Feature Importance / Insights"""

fi = pd.Series(model.feature_importances_, index=X.columns).sort_values(ascending=False)
fi.head(15).plot(kind='barh', title="Top Feature Importances")
plt.show()

"""Export model (optional)"""

#import joblib
#joblib.dump(model, "xgb_fight_predictor.pkl")